apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
        - name: kubernetes-demo-container
          image: sp013719/rest-api:v1.0.7
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: redis-service  # connect to redis-service through DNS
            - name: REDIS_PORT
              value: "6379"  # default port of Redis
  selector:
    matchLabels:
      app: demoApp